### ISSUE TITLE
Name as it should appear in Racket 8.5 Release Notes?

### ISSUE THREAD

**Issue by jbclements** [TheUnlocked/lambda-calculus-zig#1]
Please pardon my abuse of github issues as a means of reaching you. I'm John Clements, the Racket Release Manager, and I'd like to include your name in the list of contributors to the Racket 8.5 release. You can see the 8.4 release notes (https://blog.racket-lang.org/2022/02/racket-v8-4.html) for an example of what I'm talking about. My best current guess is "Trevor Paley", but I'm happy to use any name that you'd like to include.

Let me know, and feel free to close this issue....

**Comment by TheUnlocked** [comment]
@jbclements Yes, that's correct. Thank you!
